version: "3.9"

services:
  # The postgres database, service name is db
  db:  
    image: postgres # image to be used
    restart: always # always try to restart if stops running
    environment: # environment variablees
      POSTGRES_USER: baloo
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432 # port on our machine:container port

 # adminer gives UI for database
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # theme
    
    ports:
      - 3333:8080
    # 3333 is unused port to not block other services

# use docker compose up -d for background running (daemon = background)
# docker exec -it lenslocked-db-1 /usr/bin/psql -U baloo -d lenslocked
# it = interactive tty

# docker compose exec -it db psql -U baloo -d lenslocked
# db = service being used

